---
name: run ci for ztep
on: [push, pull_request]

jobs:
  build:
    name: ztep unit tests
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        zig_version: ["0.14.1", "0.15.1"]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: git checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      - name: zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig_version }} 
      - name: check zig version
        run: zig version
      - name: run all unit tests
        run: zig test src/ztep.zig
