---
name: run ci for ztep
on: [push, pull_request]

jobs:
  build:
    name: ztep unit tests
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.1
      - name: check zig version
        run: zig version
      - name: run all unit tests
        run: zig test src/ztep.zig
